# Created by Brandon Weiss on 5/22/2026

import sys

assert len(sys.argv) == 4, "Usage: python generateXML.py <Nbins> <Npulls> <tag>"

Nbins = sys.argv[1]
Npulls = sys.argv[2]
tag = sys.argv[3]

filename = 'scale_' + str(tag)

file = open('.././xml/' + filename + '.xml', 'w')
file.write('''<?xml version="1.0" ?>
<!-- ===================================================================== -->
<!-- UNOFFICIAL fake SBN-style MC for PROfit public testing.               -->
<!-- Auto-generated by make_fake_mc.py  (do NOT use for physics results).  -->
<!-- ===================================================================== -->

<mode name="nu" />
<detector name="ND" pot="1e+21"/>
<detector name="FD" pot="1e+21"/>

<channel name="numu" plotname="Fake CC #nu_{#mu} Selection">
        <bins unit="True Neutrino Energy [GeV]" min="0" max="3" nbins="''' + str(Nbins) + '''" plot="false"/>
        <bins unit="True L/E [km/GeV]" min="0" max="3" nbins="''' + str(Nbins) + '''" plot="false"/>
    <subchannel name="numu_signal" plotname="#nu_{#mu} CC" color="#99CCFF"/>
    <subchannel name="numu_background" plotname="#nu_{#mu} Backgrounds" color="#FF6961"/>
    <subchannel name="numu_cosmic" plotname="Cosmics" color="#E37400"/>
</channel>

<model tag="3+1_angles">
    <rule index="0" name="No Osc"/>
    <rule index="1" name="Numu Disappearance"/>
    <rule index="2" name="Nue Appearance"/>
    <rule index="3" name="Nue Disappearance"/>
    <parameter name="L/E" variable_index="1"/>
</model>

<MCFile treename="events/selectedNu" filename="/nevis/riverside/data/leehagaman/PROfit_files/Tutorial2025/sbnd_bnbcv_files_localtest.txt" scale = "1.0" pot="2.15692e19">
    <friend treename="events/multisigmaTree" />
    <friend treename="events/multisimTree" />
    <branch
        associated_subchannel = "nu_SBND_numu_numucc"
        model_rule            = "0"
        additional_weight     = "0.9*CC*(truePDG == 14 || truePDG == -14)*(recoE>0)"
        >
        <variable>recoE</variable>
        <variable>trueE</variable>
        <variable>trueL/(trueE*1000.0)</variable>
    </branch>
</MCFile>
           
<systematics>
    <!-- Inlcude MC stats, uncomment out to remove -->
    <systematic type="mcstat" plotname="MC Stats" tag="Other">MCStat</systematic>

''')

for i in range(int(Npulls)):
    file.write('    <systematic type="norm" plotname="dummynorm' + str(i) + '" tag="Other">dummynorm' + str(i) + ':0.02</systematic>\n')

file.write('''
    <!-- Covariance-only systematics (multisimTree) -->
    <systematic type="covariance" plotname="RPA_CCQE" tag="QE-MEC">RPA_CCQE</systematic>
    <systematic type="covariance" plotname="NormCCMEC" tag="QE-MEC">NormCCMEC</systematic>
    <systematic type="covariance" plotname="CoulombCCQE" tag="QE-MEC">CoulombCCQE</systematic>
    <systematic type="covariance" plotname="MaCCRES" tag="RES">MaCCRES</systematic>
    <systematic type="covariance" plotname="MvCCRES" tag="RES">MvCCRES</systematic>
</systematics>

''')

print('Finished making ' + filename +'.xml')