# Created by Brandon Weiss on 5/22/2026

import sys

assert len(sys.argv) == 4, "Usage: python generateXML.py <Nbins> <Npulls> <tag>"

Nbins = sys.argv[1]
Npulls = sys.argv[2]
tag = sys.argv[3]

filename = 'scale_' + str(tag)

file = open('.././xml/' + filename + '.xml', 'w')
file.write('''<?xml version="1.0" ?>
<!-- ===================================================================== -->
<!-- UNOFFICIAL fake SBN-style MC for PROfit public testing.               -->
<!-- Auto-generated by make_fake_mc.py  (do NOT use for physics results).  -->
<!-- ===================================================================== -->

<mode name="nu" />
<detector name="ND" pot="1e+21"/>

<channel name="numu" plotname="Fake CC #nu_{#mu} Selection">
        <bins unit="Random Value" min="0" max="1" nbins="''' + str(Nbins) + '''"/>
        <bins unit="Reconstructed Neutrino Energy [GeV]" min="0.1" max="3.5" nbins="34"/>
        <bins unit="True L/E [km/GeV]" min="0" max="6" nbins="60"/>
        <bins unit="True Neutrino Energy [GeV]" min="0" max="3" nbins="20" plot="false"/>
    <subchannel name="signal" plotname="#nu_{#mu} CC" color="#99CCFF"/>
</channel>

<model tag="3+1_angles">
    <rule index="0" name="No Osc"/>
    <rule index="1" name="Numu Disappearance"/>
    <rule index="2" name="Nue Appearance"/>
    <rule index="3" name="Nue Disappearance"/>
    <parameter name="L/E" variable_index="2"/>
</model>

<MCFile treename="events/selected" filename="/nevis/houston/home/markrl/fake_sbn_mc_ND.root" scale = "1.0" pot="1e+21">
    <friend treename="events/multisigmaTree" />
    <friend treename="events/multisimTree" />
    <friend treename="events/variationTree" />
    <branch
        associated_subchannel = "nu_ND_numu_signal"
        model_rule            = "1"
        additional_weight     = "mcweight*(category == 3)"
    >
        <variable>random_value</variable>
        <variable>reco_visible_energy</variable>
        <variable>true_baseline/(1000*true_neutrino_energy)</variable>
        <variable>true_neutrino_energy</variable>
    </branch>
</MCFile>
           
<systematics>
    <!-- Inlcude MC stats, uncomment out to remove -->
    <systematic type="mcstat" plotname="MC Stats" tag="Other">MCStat</systematic>

''')

for i in range(int(Npulls)):
    file.write('    <systematic type="norm" plotname="dummynorm' + str(i) + '" tag="Other">dummynorm' + str(i) + ':0.02</systematic>\n')

file.write('''
    <!-- Covariance-only systematics (multisimTree) -->
    <systematic type="covariance" plotname="RPA_CCQE" tag="QE-MEC">RPA_CCQE</systematic>
    <systematic type="covariance" plotname="NormCCMEC" tag="QE-MEC">NormCCMEC</systematic>
    <systematic type="covariance" plotname="CoulombCCQE" tag="QE-MEC">CoulombCCQE</systematic>
    <systematic type="covariance" plotname="MaCCRES" tag="RES">MaCCRES</systematic>
    <systematic type="covariance" plotname="MvCCRES" tag="RES">MvCCRES</systematic>
</systematics>

''')

print('Finished making ' + filename +'.xml')